blank_issues_enabled: false
contact_links:
  - name: Discussioni
    url: https://github.com/ondata/normattiva_2_md/discussions
    about: Per domande generali o discussioni, usa le GitHub Discussions
